// ── Nervous System Regulation Toolkit ─────────────────────────────────────────
// Condition-specific tools grounded in polyvagal theory, somatic experiencing,
// and clinical neuroscience. Each tool: { t: title, time: duration, how: steps[], why: neuroscience, when: best use case }

export const NS_CATEGORIES = [
  { id: "vagal", emoji: "🫁", label: "Vagal Toning", desc: "Activate the vagus nerve to shift from fight-or-flight to calm" },
  { id: "somatic", emoji: "🧘", label: "Somatic Grounding", desc: "Use your body to anchor your nervous system in the present" },
  { id: "activation", emoji: "⚡", label: "Healthy Activation", desc: "Safely increase energy when you're shut down or frozen" },
  { id: "coregulation", emoji: "🤝", label: "Co-Regulation", desc: "Use social connection to regulate your nervous system" },
  { id: "sensory", emoji: "🎧", label: "Sensory Reset", desc: "Use sensory input to shift your nervous system state" },
  { id: "emergency", emoji: "🧊", label: "Emergency Reset", desc: "Fast-acting tools for acute overwhelm or panic" },
];

export const NS_TOOLS = {
  // ─────────────────────────────────────────────────────────────────────────────
  // ADHD
  // ─────────────────────────────────────────────────────────────────────────────
  adhd: {
    vagal: [
      { t: "Cold Water Vagal Reset", time: "2 min", how: ["Fill a bowl with cold water and ice.", "Take a deep breath in.", "Submerge your face for 15-30 seconds.", "Come up, breathe normally. Repeat 2-3 times."], why: "Cold triggers the dive reflex, instantly activating the vagus nerve. This slams the brakes on the sympathetic nervous system, calming the racing ADHD mind without medication. Heart rate drops 10-25% within seconds.", when: "When your mind is racing and you can't slow down or focus" },
      { t: "Extended Exhale Breathing", time: "3 min", how: ["Breathe in through your nose for 4 counts.", "Hold gently for 2 counts.", "Exhale slowly through pursed lips for 8 counts.", "Repeat 6-8 cycles."], why: "Exhaling longer than inhaling directly stimulates the vagus nerve's parasympathetic branch. For ADHD brains, this counteracts the chronic low-grade sympathetic activation that makes everything feel urgent.", when: "Before tasks that require sustained focus" },
      { t: "Humming Bee Breath", time: "3 min", how: ["Close your eyes and gently place your index fingers on the cartilage of your ears.", "Inhale deeply through your nose.", "Exhale while making a low humming sound, like a bee.", "Feel the vibration in your skull and chest. Repeat 8-10 times."], why: "The vibration of humming directly stimulates the vagus nerve where it passes through the throat. The vibration also activates the middle ear muscles, part of the social engagement system that helps ADHD brains feel safe enough to focus.", when: "When you're overstimulated and need to settle" },
    ],
    somatic: [
      { t: "Bilateral Tapping", time: "3 min", how: ["Cross your arms over your chest, hands resting on opposite shoulders.", "Alternate tapping, left, right, left, right, at a steady pace.", "Keep your eyes soft or closed.", "Continue for 2-3 minutes at a rhythm that feels natural."], why: "Alternating bilateral stimulation engages both brain hemispheres, similar to EMDR. For ADHD, this rhythmic cross-body movement increases communication between hemispheres and activates the prefrontal cortex, the exact region that's underperforming.", when: "When you feel scattered and need to center yourself" },
      { t: "Gravity Grounding", time: "2 min", how: ["Sit or lie down somewhere comfortable.", "Close your eyes and feel your full body weight pressing into the surface.", "Start at your feet; feel their weight. Move up: calves, thighs, hips, back, shoulders, head.", "Imagine gravity pulling tension out through the bottom of your body."], why: "Proprioceptive input (awareness of your body's position) activates the cerebellum and somatosensory cortex, pulling attention away from the default mode network's wandering and into the present body.", when: "When you're mentally spiraling or can't sit still" },
      { t: "Progressive Muscle Squeezes", time: "5 min", how: ["Start with your feet; squeeze all muscles tight for 5 seconds.", "Release completely. Notice the contrast.", "Move up: calves, thighs, glutes, abs, hands, arms, shoulders, face.", "Squeeze each group hard for 5 seconds, then fully release."], why: "The squeeze-release cycle activates the Golgi tendon organs, which send inhibitory signals through the spinal cord. This creates a physical relaxation response that the ADHD brain can actually feel, unlike purely mental relaxation techniques.", when: "When your body feels restless and your mind won't settle" },
    ],
    activation: [
      { t: "Power Posing + Breath of Fire", time: "3 min", how: ["Stand with feet wider than hip-width, hands on hips or arms raised in a V.", "Begin breath of fire: rapid rhythmic breaths through the nose, equal inhale and exhale, 2-3 per second.", "Maintain the power stance throughout.", "Do 30 seconds on, 15 seconds normal breathing. Repeat 3 rounds."], why: "Power posing increases testosterone by 20% and decreases cortisol by 25% within 2 minutes. Breath of fire floods the prefrontal cortex with oxygen. Combined, this gives the ADHD brain the neurochemical cocktail it needs to initiate action.", when: "When you need to start something and have zero motivation" },
      { t: "Cold Shower Burst", time: "1 min", how: ["At the end of your regular shower, turn the water to cold.", "Let it hit your chest and back for 30-60 seconds.", "Focus on breathing steadily through the shock.", "End the shower and notice the alertness."], why: "Cold exposure triggers a massive norepinephrine release, 200-300% above baseline. This is the exact neurotransmitter that ADHD medications target. One minute of cold water gives your brain a natural dose of the focus chemical it's missing.", when: "Morning routine; replaces the need for stimulant-level alertness" },
    ],
    coregulation: [
      { t: "Body Double Activation", time: "ongoing", how: ["Ask someone to sit in the room while you work; they don't need to help.", "If no one is available, join a virtual body doubling session online.", "Simply having another regulated nervous system nearby is the tool.", "Their presence activates your social engagement system."], why: "The polyvagal social engagement system is activated by the presence of a calm person. Their regulated nervous system literally sends safety signals to yours through prosody, facial expression, and proximity, reducing the ADHD brain's threat detection and freeing up executive function.", when: "When you need to do focused work but can't start alone" },
      { t: "Vocal Prosody Reset", time: "2 min", how: ["Call someone you feel safe with, even a brief call.", "Focus on the melody and rhythm of their voice, not the content.", "Let your own voice soften and slow to match theirs.", "Even 2 minutes of this vocal exchange resets your nervous system."], why: "The vagus nerve controls the muscles of the middle ear and larynx. Hearing a safe person's voice tunes these muscles, activating the ventral vagal state. For ADHD brains stuck in sympathetic overdrive, this is one of the fastest paths back to regulation.", when: "When you're overwhelmed and nothing else is working" },
    ],
    sensory: [
      { t: "Weighted Pressure Reset", time: "5 min", how: ["Use a weighted blanket (10-15% of body weight), heavy backpack, or stack pillows on your chest/lap.", "Lie down or sit with the weight distributed evenly.", "Close your eyes and breathe normally for 5 minutes.", "Focus on the sensation of pressure across your body."], why: "Deep pressure touch activates the parasympathetic nervous system through mechanoreceptors in the skin. This increases serotonin by 28% and decreases cortisol by 31%. For ADHD brains, this sensory input provides the proprioceptive feedback that calms the restless nervous system.", when: "Before bed, during study sessions, or when overstimulated" },
      { t: "Rhythmic Auditory Stimulation", time: "5 min", how: ["Put on binaural beats (40Hz gamma for focus, 10Hz alpha for calm).", "Use headphones; the effect requires different frequencies in each ear.", "Close your eyes and let the rhythm entrain your brainwaves.", "Even 5 minutes shifts neural oscillation patterns."], why: "The brain naturally synchronizes to external rhythmic stimuli, a process called entrainment. 40Hz gamma binaural beats specifically increase prefrontal cortex activation, enhancing the exact brain region ADHD under-utilizes for attention and impulse control.", when: "During work or study when you need sustained focus" },
    ],
    emergency: [
      { t: "Ice Cube Grip", time: "1 min", how: ["Grab an ice cube in each hand and squeeze.", "Hold for 30-60 seconds; the cold will be intense.", "Focus entirely on the sensation.", "Release and notice how your mental state has shifted."], why: "Intense cold input hijacks the sensory cortex, interrupting the spiral of racing thoughts. The pain signal competes with and overrides the anxiety signal. Simultaneously, the cold triggers the dive reflex, dropping heart rate and activating the parasympathetic system.", when: "Acute overwhelm, emotional flooding, or panic" },
      { t: "Physiological Sigh", time: "30 sec", how: ["Take a quick double inhale through the nose (two sharp sniffs).", "Follow immediately with a long, slow exhale through the mouth.", "One cycle is often enough.", "Repeat 2-3 times if needed."], why: "Discovered by Stanford neuroscientist Andrew Huberman, the double inhale reinflates collapsed alveoli in the lungs, maximizing CO2 offloading on the exhale. This is the fastest known way to activate the parasympathetic nervous system, faster than box breathing or any other technique.", when: "Instant calm needed: before a meeting, during a meltdown, in traffic" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // ANXIETY
  // ─────────────────────────────────────────────────────────────────────────────
  anxiety: {
    vagal: [
      { t: "Extended Exhale Breathing (4-7-8)", time: "4 min", how: ["Inhale through your nose for 4 counts.", "Hold your breath gently for 7 counts.", "Exhale slowly through your mouth for 8 counts.", "Repeat for 4-6 full cycles."], why: "The extended exhale phase directly stimulates the vagus nerve's efferent fibers, shifting the autonomic balance from sympathetic (anxiety) to parasympathetic (calm). The 7-count hold allows CO2 to build slightly, which paradoxically reduces the urge to hyperventilate that drives panic.", when: "Rising anxiety, pre-panic, or racing heart" },
      { t: "Cold Water Dive Reflex", time: "2 min", how: ["Fill a bowl with cold water (add ice if available).", "Take a deep breath in.", "Submerge your face, forehead, eyes, and cheeks, for 15-30 seconds.", "Come up, breathe, repeat 2-3 times."], why: "Submerging the face activates the trigeminal nerve's ophthalmic branch, triggering the mammalian dive reflex. Heart rate drops 10-25% immediately. This overrides the sympathetic activation of anxiety more powerfully than any breathing technique alone.", when: "Panic attack or acute anxiety spike" },
      { t: "Gargling for Vagal Tone", time: "2 min", how: ["Take a large sip of water.", "Tilt your head back and gargle vigorously for 15-20 seconds.", "The goal is to gargle hard enough that your eyes water slightly.", "Repeat 3-4 times."], why: "Gargling contracts the muscles of the palate and throat, which are innervated by the vagus nerve. Vigorous gargling literally exercises the vagus nerve like a muscle, building long-term vagal tone that makes you more resilient to future anxiety.", when: "Daily practice to build anxiety resilience, or during mild anxiety" },
    ],
    somatic: [
      { t: "5-4-3-2-1 Sensory Grounding", time: "3 min", how: ["Name 5 things you can SEE; describe their details.", "Name 4 things you can TOUCH; feel their textures right now.", "Name 3 things you can HEAR; even subtle background sounds.", "Name 2 things you can SMELL.", "Name 1 thing you can TASTE."], why: "Anxiety lives in the future; your amygdala is projecting threat forward in time. Sensory grounding forces the brain into present-moment processing by activating the somatosensory cortex, which competes with and dampens amygdala activation. You cannot be sensorily present and anxiously future-focused simultaneously.", when: "Dissociation, derealization, or spiraling worry" },
      { t: "Orienting Response", time: "2 min", how: ["Slowly turn your head to the right. Let your eyes lead.", "Find an object and study it: color, shape, texture.", "Slowly turn to the left. Find another object and study it.", "Continue slowly scanning your environment for 2 minutes.", "Let your neck muscles relax as you turn."], why: "The orienting response is a primitive survival mechanism: when an animal scans its environment and finds no threat, the nervous system completes its defensive cycle and returns to safety. Anxious brains skip this step, staying in threat mode. Deliberate orienting tells your brainstem: 'I've checked; it's safe.'", when: "After a startle, in a new environment, or when anxiety feels physical" },
      { t: "Butterfly Hug", time: "3 min", how: ["Cross your arms over your chest, fingertips resting below your collarbones.", "Alternate tapping, left, right, left, right, slowly and gently.", "Close your eyes and focus on the sensation.", "Continue for 2-3 minutes at whatever speed feels soothing."], why: "Bilateral alternating stimulation activates both hemispheres and engages the thalamus as a relay station. This mimics the neural pattern of REM sleep, the state where your brain naturally processes and calms emotional memories. It's the mechanism behind EMDR therapy.", when: "After a triggering event or during anticipatory anxiety" },
    ],
    activation: [
      { t: "Gentle Rhythmic Movement", time: "5 min", how: ["Stand and gently sway side to side, like a tree in the breeze.", "Let your arms hang loose and swing naturally.", "Gradually increase the movement to gentle bouncing or swaying.", "Match your breathing to the rhythm."], why: "Rhythmic movement activates the vestibular system and cerebellum, which have direct inhibitory connections to the amygdala. Gentle activation is key for anxiety; too intense triggers more sympathetic response. This Goldilocks-level movement downregulates threat detection while increasing embodiment.", when: "When anxiety has you frozen or stuck in your head" },
      { t: "Vagal Toning Walk", time: "10 min", how: ["Walk at a comfortable pace, not exercise-level.", "Breathe in for 4 steps, out for 6 steps.", "Soften your gaze; look at the horizon, not the ground.", "Let your arms swing naturally. Notice the bilateral rhythm."], why: "Walking engages bilateral cross-body movement, activating both hemispheres. The extended exhale breath pattern stimulates the vagus nerve. Soft gaze activates panoramic vision (parasympathetic) rather than tunnel vision (sympathetic). This triple combination is one of the most researched anti-anxiety interventions.", when: "Daily practice, or when anxiety is building but not acute" },
    ],
    coregulation: [
      { t: "Safe Person Breathing Sync", time: "3 min", how: ["Sit next to or across from someone you feel safe with.", "Ask them to breathe slowly and steadily.", "Match your breathing to theirs; inhale when they inhale.", "Maintain soft eye contact or place a hand on their arm.", "Let their regulated rhythm guide yours."], why: "Mirror neurons in the premotor cortex fire when we observe someone else's breathing pattern, creating an automatic tendency to synchronize. A calm person's nervous system literally entrains an anxious one through this neural coupling. This is why babies calm when held by a regulated parent.", when: "During anxiety when breathing exercises alone aren't working" },
      { t: "Ventral Vagal Voice Connection", time: "5 min", how: ["Call or sit with someone whose voice makes you feel safe.", "Listen to the melody and rhythm of their speech, not just the words.", "Respond with your own softened voice.", "Notice how your chest and throat relax as you engage."], why: "The ventral vagal complex controls the muscles of the face, middle ear, and larynx simultaneously. Hearing a prosodic (melodic, warm) voice tunes the middle ear to human speech frequencies, activating the social engagement system. This is the polyvagal shortcut to safety; your ears tell your brain the environment is safe.", when: "When you feel alone in your anxiety" },
    ],
    sensory: [
      { t: "Weighted Blanket Cocoon", time: "10 min", how: ["Wrap yourself tightly in a weighted blanket (10-15% body weight).", "Curl into a comfortable position.", "Place your hands over your heart or belly.", "Breathe normally and let the weight do the work."], why: "Deep pressure touch activates the parasympathetic nervous system through Pacinian corpuscles and Ruffini endings in the skin. Research shows weighted blankets reduce anxiety by 33% and cortisol by 31%. The pressure mimics the containment of being held, activating the same neural pathways.", when: "Evening anxiety, insomnia, or after a stressful day" },
      { t: "Lavender + Cold Air Reset", time: "3 min", how: ["Apply lavender essential oil to wrists and temples (or inhale from the bottle).", "Step outside or open a window for cool fresh air.", "Take 5 deep breaths, inhaling the lavender and cool air.", "Close your eyes between breaths."], why: "Linalool in lavender directly modulates GABA-A receptors, the same receptors targeted by benzodiazepines, without the side effects. Cold air stimulates trigeminal nerve endings in the face, activating the dive reflex. The combination provides chemical and neural calming simultaneously.", when: "Mild to moderate anxiety, especially before sleep" },
    ],
    emergency: [
      { t: "Physiological Sigh", time: "30 sec", how: ["Take a quick double inhale through the nose (two sharp sniffs in a row).", "Immediately follow with one long, slow exhale through the mouth.", "One cycle often produces immediate calm.", "Repeat 2-3 times if the first isn't enough."], why: "The double inhale reinflates collapsed alveoli in the lungs, maximizing the surface area for gas exchange. The long exhale then offloads maximum CO2, which directly reduces the blood acidity that drives the physical sensations of panic. This is the single fastest known method to activate the parasympathetic nervous system.", when: "Panic attack, acute anxiety spike, or any moment you need instant calm" },
      { t: "TIPP: Temperature", time: "2 min", how: ["Fill a ziplock bag with ice water or grab frozen vegetables.", "Hold against your face: forehead, cheeks, and around eyes.", "Or: submerge hands in ice water up to wrists.", "Hold for 30-60 seconds. Breathe slowly through the discomfort."], why: "Temperature is the T in the DBT TIPP skill because it's the fastest way to change body chemistry. Cold on the face activates the dive reflex (heart rate drops 10-25%). Cold on the hands activates temperature-sensitive afferent nerves that signal the brainstem to shift from sympathetic to parasympathetic dominance.", when: "Full panic attack or emotional crisis; this works in under 60 seconds" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // DEPRESSION
  // ─────────────────────────────────────────────────────────────────────────────
  depression: {
    vagal: [
      { t: "Humming Vagal Activation", time: "3 min", how: ["Sit comfortably and close your eyes.", "Inhale deeply through your nose.", "Exhale while humming at a low pitch; feel the vibration in your chest.", "Continue for 3 minutes, finding the pitch that vibrates most."], why: "Depression often involves dorsal vagal shutdown, the nervous system's most primitive freeze response. Humming vibrates the vagus nerve where it passes through the throat, stimulating the ventral vagal pathway that governs social engagement and emotional availability. This gently pulls you out of shutdown without the overwhelm of intense activation.", when: "Morning sluggishness, emotional numbness, or feeling shut down" },
      { t: "Singing or Chanting", time: "5 min", how: ["Sing along to a familiar song, anything you know the words to.", "Focus on projecting your voice, not sounding good.", "If singing feels like too much, chant 'Om' or hum a melody.", "Feel the vibration in your chest, throat, and face."], why: "Singing requires coordinated control of the larynx, diaphragm, and facial muscles, all vagally innervated. This combination provides the strongest vagal stimulation of any daily activity. Singing also releases oxytocin and reduces cortisol, directly counteracting the neurochemical signature of depression.", when: "Daily practice, especially in the morning or during a low mood dip" },
    ],
    somatic: [
      { t: "Gentle Body Scan", time: "5 min", how: ["Lie down and close your eyes.", "Start at the top of your head; just notice what's there. No judgment.", "Slowly move attention down: forehead, jaw, neck, shoulders, chest, belly, hips, legs, feet.", "At each area, breathe into it and soften. Don't try to change anything.", "If you feel nothing, that's information; notice the numbness."], why: "Depression often manifests as disconnection from the body, a dorsal vagal freeze that numbs physical sensation. Body scanning slowly reestablishes the interoceptive awareness that the insula needs to process emotion. You're literally rebuilding the brain-body connection that depression disrupts.", when: "When you feel numb, disconnected, or 'empty'" },
      { t: "Feet on Earth Grounding", time: "3 min", how: ["Stand barefoot on grass, soil, or a cool floor.", "Press your feet firmly into the ground. Spread your toes.", "Shift your weight slowly: left foot, right foot, heels, toes.", "Feel the surface texture, temperature, and your body's weight."], why: "The soles of the feet have the highest density of mechanoreceptors in the body. Stimulating them sends massive proprioceptive input to the cerebellum and somatosensory cortex, pulling the brain out of the ruminative default mode network and into present-body awareness. Earthing also reduces cortisol and inflammation markers.", when: "When you're stuck in rumination or can't get out of your head" },
    ],
    activation: [
      { t: "Micro-Movement Activation", time: "3 min", how: ["Start lying down or sitting, wherever you are.", "Begin with the smallest possible movement: wiggle your fingers.", "Gradually increase: roll your wrists, shrug your shoulders, roll your neck.", "If you can, stand up. Gently bounce or sway.", "Each movement is a victory; don't aim for exercise."], why: "Depression's dorsal vagal shutdown makes large movements feel impossible. Micro-movements work because they recruit small motor units first, gradually increasing neural activation without triggering the freeze response. Each tiny movement sends proprioceptive signals that tell the brainstem 'I'm alive, I'm moving', the opposite of shutdown.", when: "When getting out of bed feels impossible" },
      { t: "Morning Light + Movement", time: "10 min", how: ["Within 30 minutes of waking, get outside or to a bright window.", "Walk slowly for 10 minutes; pace doesn't matter.", "Look toward the sky (not directly at the sun) to get light into your eyes.", "Swing your arms and breathe through your nose."], why: "Morning light exposure suppresses melatonin and triggers a cortisol pulse that sets the circadian clock. This single intervention has been shown to be as effective as SSRIs for mild-moderate depression in clinical trials. The walking adds bilateral stimulation and mild cardiovascular activation, boosting BDNF and serotonin.", when: "Every single morning; this is the #1 non-pharmaceutical antidepressant" },
      { t: "Shake It Off", time: "3 min", how: ["Stand with feet hip-width apart and slightly bent knees.", "Begin bouncing gently, letting your whole body shake.", "Let your arms, jaw, and shoulders go completely loose.", "Increase intensity if it feels good. Make sounds if they come.", "After 2-3 minutes, stop and stand still. Notice the aliveness in your body."], why: "Animals in the wild shake after a threat to discharge the freeze response. Humans suppress this reflex. Intentional shaking activates the same tremor mechanism, releasing stored tension from the psoas and diaphragm, two muscles that lock during dorsal vagal shutdown. The tingling 'aliveness' afterward is your ventral vagal system coming back online.", when: "When you feel heavy, stuck, or physically weighed down by depression" },
    ],
    coregulation: [
      { t: "Parallel Presence", time: "ongoing", how: ["Ask someone to simply be in the same room as you.", "They don't need to talk, help, or fix anything.", "Just their physical presence is the intervention.", "If alone, video call someone and both do your own activities."], why: "Polyvagal theory shows that a regulated nervous system in proximity literally broadcasts safety cues through facial expression, breathing rhythm, and postural signals. A depressed nervous system in dorsal vagal shutdown needs these external safety cues to begin shifting; you cannot always generate them internally when depressed.", when: "When you can't motivate yourself and isolation is making it worse" },
    ],
    sensory: [
      { t: "Warm Water Immersion", time: "10 min", how: ["Fill a bath or basin with warm (not hot) water, around 100°F/38°C.", "Immerse as much of your body as possible.", "Add Epsom salts if available (magnesium absorbs through skin).", "Breathe slowly and let the warmth soften your muscles."], why: "Warm water immersion raises core body temperature, which triggers a compensatory cooling response that includes serotonin and endorphin release. The hydrostatic pressure of water provides whole-body deep pressure touch. Research shows a single warm bath produces antidepressant effects comparable to exercise.", when: "Evening routine, or anytime depression feels heavy in the body" },
      { t: "Upbeat Music Entrainment", time: "5 min", how: ["Put on a song with a tempo of 100-130 BPM (upbeat but not frantic).", "Use headphones for maximum effect.", "Let your body respond however it wants: nod, tap, sway.", "Don't force energy; just let the rhythm influence you."], why: "Auditory rhythm entrains neural oscillations through the auditory cortex-motor cortex connection. Music at 100-130 BPM synchronizes brainwaves to beta frequency (alertness), counteracting the excess theta/delta waves (drowsiness) seen in depression. Music also triggers dopamine release in the nucleus accumbens.", when: "When you need a gentle energy lift without forcing motivation" },
    ],
    emergency: [
      { t: "Opposite Action Movement", time: "2 min", how: ["Depression says: stay in bed. Do the opposite; stand up.", "Depression says: stay inside. Walk to the door and open it.", "Depression says: don't reach out. Send one text.", "Each opposite action is a micro-win against the freeze response."], why: "Behavioral activation is the most evidence-based depression intervention alongside medication. The dorsal vagal freeze makes inaction feel safe, but it perpetuates the cycle. Each opposite action generates a small dopamine hit from novelty and breaks the freeze loop. The action doesn't need to be big; just opposite.", when: "When depression is pulling you into complete withdrawal" },
      { t: "Physiological Sigh + Splash", time: "1 min", how: ["Double inhale through the nose (two quick sniffs).", "Long slow exhale through the mouth.", "Immediately splash cold water on your face.", "Repeat the sigh one more time."], why: "The physiological sigh activates the parasympathetic system while the cold water triggers the dive reflex. For depression, this combination serves a different purpose than for anxiety; it interrupts the dorsal vagal freeze and forces a momentary shift in nervous system state, creating a window to take one small action.", when: "When numbness or shutdown is complete and you need to feel something" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BIPOLAR
  // ─────────────────────────────────────────────────────────────────────────────
  bipolar: {
    vagal: [
      { t: "Rhythmic Breathing Pacer", time: "5 min", how: ["Breathe in for 5 counts, out for 5 counts, equal rhythm.", "Use a visual pacer: watch a clock's second hand or an app.", "Maintain this exact rhythm for 5 full minutes.", "The consistency is more important than depth."], why: "Bipolar involves oscillation between sympathetic overdrive (mania) and dorsal vagal shutdown (depression). Equal-ratio breathing is uniquely suited because it doesn't push toward activation or deactivation; it trains the vagus nerve to find center. This builds the regulatory flexibility that bipolar brains need most.", when: "Daily practice, especially during mood transitions" },
      { t: "Slow Gargling", time: "2 min", how: ["Take a sip of water and gargle gently.", "Make it slow and controlled, not vigorous.", "Focus on sustaining the gargle for 15-20 seconds per round.", "Repeat 4-5 times, resting between rounds."], why: "Gargling activates the pharyngeal branch of the vagus nerve. For bipolar, the slow, controlled version is key; it builds vagal tone without the intense stimulation that could trigger hypomanic activation. Think of it as physical therapy for your vagus nerve.", when: "Morning routine to build baseline regulation" },
    ],
    somatic: [
      { t: "Pendulation Practice", time: "5 min", how: ["Sit comfortably. Notice an area of tension or discomfort in your body.", "Now find an area that feels neutral or pleasant.", "Slowly shift your attention between the two: uncomfortable, then comfortable.", "Spend 30 seconds in each spot. Notice how the uncomfortable area shifts."], why: "Pendulation, developed by Peter Levine (Somatic Experiencing), trains the nervous system to move fluidly between states rather than getting stuck. For bipolar, this directly addresses the core deficit: the inability to smoothly transition between activation levels. You're teaching your nervous system that it can move without crashing.", when: "When you feel a mood shift starting" },
      { t: "Anchoring Body Scan", time: "5 min", how: ["Place one hand on your chest, one on your belly.", "Feel your heartbeat and breathing rhythm.", "Ask: 'What speed am I running at right now? 1 (shut down) to 10 (manic)?'", "Don't try to change it; just identify your current state.", "This awareness is the regulation tool."], why: "Interoceptive awareness, the ability to accurately sense internal body states, is reduced in bipolar disorder. Research shows that people in early mania often don't recognize their escalating physiology. This practice rebuilds the internal monitoring that serves as an early warning system.", when: "3 times daily as a mood check-in: morning, midday, evening" },
    ],
    activation: [
      { t: "Steady-State Walking", time: "15 min", how: ["Walk at a moderate, steady pace, not too fast, not too slow.", "Set a timer so you don't extend based on mood.", "Maintain the same pace the entire time.", "No music that could amplify your current mood state."], why: "Steady-state cardio is the safest exercise modality for bipolar. High-intensity exercise can trigger mania through excessive catecholamine release. Walking at moderate pace provides BDNF and serotonin benefits without the dopamine spike that could destabilize mood. The fixed duration prevents hypomanic over-extension.", when: "Daily, but especially when you feel mood shifting in either direction" },
    ],
    coregulation: [
      { t: "Trusted Person Mood Check", time: "5 min", how: ["Ask a trusted person: 'How do I seem to you today? What's my energy level?'", "Listen without defending. Their outside perspective is data.", "Compare their observation to your internal self-assessment.", "If there's a mismatch, that's important clinical information."], why: "Anosognosia (lack of illness awareness) is a neurological feature of mania; the prefrontal cortex is too activated to accurately self-monitor. External regulation through a trusted person's assessment provides the reality-testing that your own brain cannot during mood episodes. This isn't about control; it's about having an external nervous system mirror.", when: "Daily check-in, and especially when you suspect a mood shift" },
    ],
    sensory: [
      { t: "Consistent Sensory Environment", time: "ongoing", how: ["Keep lighting consistent: dim in the evening, bright in the morning.", "Reduce screen brightness after 8pm.", "Use the same calming scent daily (lavender, cedarwood).", "Keep background noise consistent: white noise or soft ambient music."], why: "The bipolar nervous system is exquisitely sensitive to environmental stimulation. Sensory consistency reduces the allostatic load (total environmental stress) that can trigger episodes. Consistent cues also entrain circadian rhythms, and circadian disruption is the #1 trigger for bipolar episodes.", when: "Always; this is a lifestyle tool, not an acute intervention" },
    ],
    emergency: [
      { t: "HALT Check + Containment", time: "3 min", how: ["Ask yourself: Am I Hungry? Angry? Lonely? Tired?", "Address whichever applies with the simplest possible action.", "If the mood escalation isn't explained by HALT, it may be an episode.", "Call your designated support person. This is not weakness; this is your early warning system working."], why: "HALT factors are the four physiological states that most commonly destabilize bipolar mood. Addressing them first eliminates false alarms. If mood escalation persists after HALT needs are met, it's likely a neurobiological shift requiring clinical attention. Having a pre-designated support person removes the decision-making burden when your prefrontal cortex is compromised.", when: "When you notice a significant mood shift in either direction" },
      { t: "Physiological Sigh", time: "30 sec", how: ["Double inhale through the nose (two quick sniffs).", "One long exhale through the mouth.", "Repeat 2-3 times.", "This works for both anxiety-mania and depressive episodes."], why: "The physiological sigh is state-independent; it helps regardless of which direction your mood has shifted. For manic activation, it engages the parasympathetic brake. For depressive freeze, the double inhale provides mild arousal before the calming exhale. It's the universal emergency reset.", when: "Any acute mood destabilization" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // PTSD
  // ─────────────────────────────────────────────────────────────────────────────
  ptsd: {
    vagal: [
      { t: "Voo Breath (Peter Levine)", time: "3 min", how: ["Inhale deeply through your nose.", "Exhale while making a deep 'Voooooo' sound, like a foghorn.", "Feel the vibration in your belly and chest.", "Let the sound be as low and rumbly as possible.", "Repeat 8-10 times."], why: "The 'Voo' sound vibrates the abdominal branch of the vagus nerve more effectively than humming. Peter Levine developed this specifically for trauma because it accesses the gut-brain axis where trauma is often stored somatically. The deep vibration signals safety to the enteric nervous system, your 'second brain.'", when: "When you feel the body going into freeze or hypervigilance" },
      { t: "Extended Exhale with Resistance", time: "3 min", how: ["Inhale through your nose for 4 counts.", "Exhale through pursed lips (like blowing through a straw) for 8 counts.", "The resistance of pursed lips is important; it slows the exhale.", "Repeat for 6-8 cycles."], why: "The resistance of pursed-lip breathing creates back-pressure in the airways that stimulates baroreceptors, which signal the vagus nerve to lower heart rate. For PTSD, this engages the ventral vagal brake more forcefully than open-mouth exhaling, providing stronger parasympathetic activation to counter hyperarousal.", when: "Hypervigilance, flashback onset, or racing heart" },
    ],
    somatic: [
      { t: "Orienting to Safety", time: "3 min", how: ["Slowly turn your head to one side. Let your eyes scan.", "Find something that catches your attention; really look at it.", "Slowly turn to the other side. Find another object.", "Name what you see: color, shape, texture.", "Tell yourself: 'Right now, in this moment, I am safe.'"], why: "PTSD keeps the nervous system locked in a defensive orienting response, constantly scanning for threat. Deliberate slow orienting with the conscious label 'I am safe' provides the completion signal that the trauma interrupted. Your brainstem needs sensory evidence of present safety to release the past-tense threat.", when: "After a trigger, flashback, or when hypervigilance is high" },
      { t: "Containment Visualization", time: "5 min", how: ["Close your eyes and imagine a strong container: a vault, a locked chest, a force field.", "Visualize placing today's difficult feelings or memories inside it.", "See yourself closing and locking it. It holds everything safely.", "Tell yourself: 'These are real, but they don't need to be out right now.'", "Open your eyes and orient to the room."], why: "Containment isn't suppression; it's a somatic therapy technique that gives the nervous system permission to defer processing to a safe time (like therapy). Trauma overwhelms because it feels boundless. Containment creates a boundary, allowing the prefrontal cortex to manage titrated exposure rather than flooding.", when: "When trauma memories intrude outside of therapy sessions" },
      { t: "Grounding Through Feet", time: "2 min", how: ["Stand or sit with feet flat on the ground.", "Press your feet firmly into the floor. Feel the pressure.", "Shift weight: left, right, heels, toes.", "Stamp gently 3-4 times per foot.", "Tell yourself: 'I have ground beneath me. I am here.'"], why: "The feet contain dense mechanoreceptor networks that feed directly to the somatosensory cortex. During dissociation or flashbacks, activating these receptors creates a strong 'present moment' signal that competes with the trauma memory's hijacking of the sensory cortex. You're giving your brain real-time data that overrides past-tense data.", when: "Dissociation, flashback, or feeling 'not in your body'" },
    ],
    activation: [
      { t: "Titrated Pendulation", time: "5 min", how: ["Notice where you feel tension or activation in your body (don't go to the worst spot).", "Stay with it briefly, just 10-15 seconds.", "Now shift attention to a neutral or pleasant body area.", "Stay there for 30 seconds. Breathe.", "Return to the activation area. Notice if it shifted at all."], why: "Full-intensity trauma processing can retraumatize. Titrated pendulation, developed in Somatic Experiencing, processes activation in small doses, allowing the nervous system to discharge incrementally. Each pendulation cycle completes a micro-portion of the thwarted fight-or-flight response, gradually reducing the stored activation.", when: "When body sensations related to trauma arise outside of therapy" },
      { t: "Push Against the Wall", time: "2 min", how: ["Stand facing a wall with hands flat against it at shoulder height.", "Push hard against the wall, as hard as you can, for 10 seconds.", "Release and notice the sensation in your arms and chest.", "Repeat 3-5 times.", "Shake out your hands between pushes."], why: "Trauma often involves thwarted self-defense; the body wanted to push away or fight back but couldn't. Wall pushing completes this thwarted motor response. The isometric contraction and release also discharges the muscular tension that the freeze response trapped in your body. You're letting your body finish what it started.", when: "When you feel the urge to fight or feel powerless" },
    ],
    coregulation: [
      { t: "Safe Person Proximity", time: "ongoing", how: ["Identify people whose presence makes your body relax (not just your mind).", "Spend time in their physical proximity, even without talking.", "Notice: does your breathing slow? Do your shoulders drop?", "If yes, their nervous system is co-regulating yours."], why: "Stephen Porges' research shows that traumatized nervous systems have difficulty self-regulating because the neuroception of safety is impaired. A regulated person's facial expressions, voice prosody, and breathing patterns transmit safety signals that bypass cognitive processing, directly influencing your autonomic state.", when: "Ongoing, especially after triggering events" },
    ],
    sensory: [
      { t: "Bilateral Music Listening", time: "10 min", how: ["Use headphones and listen to music that alternates between left and right ears.", "Or: listen to any music while slowly tapping alternating knees.", "Let your eyes soften or close.", "Focus on the back-and-forth sensation."], why: "Bilateral auditory stimulation mimics the neural pattern of REM sleep and EMDR, both of which facilitate trauma memory reprocessing. The alternating input between hemispheres helps integrate fragmented trauma memories that are stored as sensory fragments rather than coherent narratives.", when: "After a triggering day, or as a daily regulation practice" },
      { t: "Grounding Scent Anchor", time: "1 min", how: ["Choose a scent that is NOT associated with any trauma memory.", "Keep it accessible: essential oil on a bracelet, scented lotion, a spice.", "When triggered, immediately smell it. Inhale deeply 3-5 times.", "Pair it with the thought: 'I am here, now, and I am safe.'"], why: "The olfactory nerve is the only cranial nerve that connects directly to the limbic system without passing through the thalamus. Scent bypasses cognitive processing and directly accesses the amygdala and hippocampus. A safety-associated scent can interrupt a flashback at the neurological level before conscious thought is possible.", when: "Flashback onset or any trauma trigger" },
    ],
    emergency: [
      { t: "Dive Reflex + Grounding", time: "2 min", how: ["Fill hands with cold water or grab ice.", "Press cold water to your face: forehead, cheeks, eyes.", "While holding: stamp your feet firmly on the ground.", "Name out loud: 'My name is ___. I am in ___. The year is ___."], why: "This combines three powerful interventions: the dive reflex (cold → vagal activation → heart rate drops), proprioceptive grounding (feet → present moment), and temporal orientation (naming → prefrontal cortex activation). Together they create a triple-lock on the present moment, pulling you out of the past-tense trauma replay.", when: "Active flashback or severe dissociation" },
      { t: "Physiological Sigh + Orientation", time: "1 min", how: ["Double inhale through the nose (two sniffs).", "Long exhale through the mouth.", "Immediately look around and name 5 objects you see.", "Touch something nearby; describe its texture out loud.", "Repeat the sigh if needed."], why: "The physiological sigh provides the fastest parasympathetic activation. Pairing it with immediate sensory orientation prevents the nervous system from sliding back into the trauma response. Speaking out loud engages the ventral vagal speech circuits, further anchoring you in the present social engagement system.", when: "Acute trigger, flashback, or panic" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // OCD
  // ─────────────────────────────────────────────────────────────────────────────
  ocd: {
    vagal: [
      { t: "Structured Box Breathing", time: "4 min", how: ["Inhale for 4 counts.", "Hold for 4 counts.", "Exhale for 4 counts.", "Hold empty for 4 counts.", "Repeat for 4 minutes exactly (use a timer)."], why: "OCD brains crave structure and predictability; unstructured breathing exercises can feel like 'another thing to get right.' Box breathing's rigid structure satisfies the OCD brain's need for order while simultaneously activating the vagus nerve. The predictable pattern reduces the uncertainty that fuels OCD anxiety.", when: "Before or during ERP exercises, or when urge to ritualize is high" },
      { t: "Cold Wrist Reset", time: "1 min", how: ["Run cold water over your inner wrists for 30-60 seconds.", "The inner wrists have major blood vessels close to the surface.", "Focus on the cold sensation, nothing else.", "Dry your wrists and notice the shift."], why: "Cold on the wrists rapidly cools blood flowing to the brain, reducing the thermal component of anxiety. The sharp sensory input also engages the somatosensory cortex, competing with the anterior cingulate cortex's obsessive loop. This provides a physical interruption to the OCD cycle without becoming a ritual itself.", when: "When an obsessive thought loop has started and you need a circuit breaker" },
    ],
    somatic: [
      { t: "Body-Based ERP Support", time: "5 min", how: ["When facing an obsessive trigger, notice where anxiety lives in your body.", "Place your hand there: chest, stomach, throat.", "Breathe into that area. Don't try to make the anxiety disappear.", "Tell yourself: 'This is anxiety. It is uncomfortable but not dangerous.'", "Stay with the sensation for 5 minutes. Watch it change on its own."], why: "ERP (Exposure Response Prevention) is the gold standard for OCD, but the body's alarm response can make it unbearable. Adding somatic awareness creates a container for the anxiety; you're not fighting it or performing a ritual, you're observing it in your body. This builds distress tolerance and teaches the nervous system that anxiety peaks and passes.", when: "During ERP practice or when resisting a compulsion" },
      { t: "Grounding Through Touch", time: "2 min", how: ["Find an object with interesting texture: a stone, fabric, bark.", "Hold it and explore every detail with your fingers.", "Notice temperature, weight, texture, edges.", "Keep your attention on physical sensation, not on thoughts."], why: "OCD traps attention in the cognitive loop between the orbitofrontal cortex and caudate nucleus. Tactile grounding routes attention through the somatosensory cortex instead, breaking the loop at the neural level. The key is that this isn't a ritual; it's sensory redirection.", when: "When caught in a thought loop and need to interrupt it" },
    ],
    activation: [
      { t: "Structured Movement Sequence", time: "5 min", how: ["Do a set sequence: 10 jumping jacks, 10 squats, 10 arm circles, 30-second plank.", "The sequence is always the same; predictability matters.", "Focus on counting and form.", "End with 5 deep breaths."], why: "Physical exercise increases serotonin, the neurotransmitter most implicated in OCD. The structured format satisfies OCD's need for order without becoming compulsive, because the sequence has a clear beginning and end. The counting engages working memory, which competes with the obsessive loop for prefrontal resources.", when: "When OCD anxiety is building and you need a healthy outlet" },
    ],
    coregulation: [
      { t: "Externalize the OCD Voice", time: "5 min", how: ["Tell a trusted person: 'My OCD is telling me ___.'", "Have them respond: 'That's the OCD talking, not you.'", "Practice hearing the difference between your voice and OCD's voice.", "Let their calm certainty anchor you."], why: "Externalizing OCD, treating it as a separate entity, is an evidence-based therapeutic technique. When another person confirms 'that's the OCD,' it activates your social engagement system and provides external reality-testing that your overactive anterior cingulate cortex cannot provide internally.", when: "When you can't tell if a thought is OCD or a real concern" },
    ],
    sensory: [
      { t: "Predictable Sensory Routine", time: "5 min", how: ["Create a brief sensory ritual that isn't OCD-related.", "Example: light a specific candle, apply hand cream, listen to one specific song.", "Do it at the same time daily.", "This gives your brain the predictability it craves through a healthy channel."], why: "OCD involves an overactive habit loop (caudate nucleus → orbitofrontal cortex → thalamus). Healthy sensory routines satisfy the brain's need for predictable patterns through a non-pathological route. Over time, the brain learns to get its 'certainty fix' from healthy rituals rather than compulsions.", when: "Daily, as a replacement for the certainty-seeking that drives compulsions" },
    ],
    emergency: [
      { t: "Delay and Distract (2-Minute Rule)", time: "2 min", how: ["When the compulsion urge hits, set a timer for 2 minutes.", "During those 2 minutes, do something sensory: cold water on face, intense taste (sour candy), strong smell.", "When the timer ends, check: is the urge the same, more, or less?", "If less, wait another 2 minutes. Urges peak and pass."], why: "OCD urges follow a predictable curve: they spike, peak, and decline. The anxiety feels unbearable because your brain predicts it will escalate forever. The 2-minute delay provides evidence that it peaks and passes. The sensory distraction engages competing neural circuits, making the wait bearable. Each successful delay weakens the compulsion pathway.", when: "When the urge to perform a compulsion feels overwhelming" },
      { t: "Physiological Sigh", time: "30 sec", how: ["Double inhale through the nose (two sniffs).", "Long slow exhale through the mouth.", "Repeat 2-3 times.", "Then: name 3 things you can see."], why: "The fastest parasympathetic activation available. For OCD, pair it with visual orienting to prevent the mind from immediately returning to the obsessive loop. The exhale calms the body; the visual task redirects the mind.", when: "Acute OCD spike or before touching a trigger" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // BPD
  // ─────────────────────────────────────────────────────────────────────────────
  bpd: {
    vagal: [
      { t: "TIPP: Temperature + Paced Breathing", time: "3 min", how: ["Fill a ziplock bag with ice or grab frozen vegetables.", "Hold against your face, forehead and cheeks, for 30 seconds.", "Then begin paced breathing: in for 4, out for 6.", "Alternate between cold and breathing for 3 minutes."], why: "TIPP is the cornerstone DBT distress tolerance skill. Temperature activates the dive reflex, dropping heart rate 10-25% immediately. Paced breathing sustains the parasympathetic shift. For BPD, where emotional intensity can go from 0-100 in seconds, this combination provides the fastest possible deescalation.", when: "Emotional crisis, intense anger, or urge to self-harm" },
      { t: "Extended Exhale with Sound", time: "3 min", how: ["Inhale through nose for 4 counts.", "Exhale through mouth for 8 counts while making a soft 'shhhh' or 'haaa' sound.", "The sound slows the exhale and provides auditory feedback.", "Repeat for 3 minutes."], why: "Adding sound to the exhale serves dual purposes: it vibrates the vagus nerve (vagal toning) and provides auditory self-soothing. BPD often involves impaired self-soothing capacity; the sound gives the auditory cortex something calming to process while the extended exhale activates the parasympathetic system.", when: "Rising emotional intensity or difficulty self-soothing" },
    ],
    somatic: [
      { t: "Radical Acceptance Body Practice", time: "5 min", how: ["Sit and notice where emotional pain lives in your body.", "Place both hands on that area.", "Say internally: 'This pain is real. I don't have to fight it.'", "Breathe into your hands for 1 minute.", "Then say: 'This moment is what it is. I can survive this feeling.'"], why: "BPD involves intense emotional pain coupled with the belief that the pain is intolerable. Radical acceptance, feeling the emotion in the body without resistance, activates the prefrontal cortex's regulatory circuits. Research shows that labeling and accepting an emotion reduces amygdala activation by up to 50% compared to suppressing it.", when: "When emotions feel unbearable and the urge to act on them is strong" },
      { t: "Paired Muscle Relaxation (TIPP-P)", time: "5 min", how: ["Tense your facial muscles hard for 5 seconds while breathing in.", "Release completely while breathing out slowly. Notice the drop.", "Move to shoulders: tense 5 seconds, release with exhale.", "Continue: arms, hands (make fists), abs, legs, feet.", "Each release should feel like letting go of the emotion."], why: "The P in TIPP. Pairing muscle tension with inhale and release with exhale conditions the body to associate relaxation with exhalation. For BPD, the physical tension provides a safe outlet for emotional intensity while the release teaches the nervous system that intense states can resolve; they don't have to be acted on.", when: "When emotional intensity is high and you need to ride the wave" },
    ],
    activation: [
      { t: "Intense Exercise Burn-Off", time: "10 min", how: ["Do the most physically intense exercise available to you.", "Options: sprinting, burpees, jump squats, boxing a pillow, running stairs.", "Push to breathlessness; the intensity is the point.", "After 10 minutes, stop and notice the emotional shift."], why: "BPD emotional intensity often involves a massive catecholamine surge (adrenaline, norepinephrine). Intense exercise metabolizes these chemicals through the pathway they were designed for: physical action. The exercise doesn't suppress the emotion; it gives the body's stress response its intended outlet. Post-exercise endorphins then provide natural emotional relief.", when: "Intense anger, emotional overwhelm, or urge to act destructively" },
    ],
    coregulation: [
      { t: "DEAR MAN with a Safe Person", time: "5 min", how: ["When emotionally activated, go to your safe person.", "Describe what happened (facts only, no judgment).", "Express how you feel using 'I' statements.", "Assert what you need from them right now.", "Let them respond. Their calm voice is co-regulating you."], why: "DBT's interpersonal effectiveness skill, adapted for co-regulation. BPD often involves fear of abandonment that makes reaching out feel dangerous. Having a structured script (DEAR MAN) reduces the cognitive load of communication during emotional crises. The safe person's regulated nervous system provides the external stabilization that internal regulation alone cannot achieve.", when: "When emotions feel too big to handle alone" },
    ],
    sensory: [
      { t: "Sensory Grounding Kit", time: "varies", how: ["Build a physical kit with: ice cubes, sour candy, a strong essential oil, a rough-textured cloth, a rubber band for snapping (on wrist, gently).", "When emotionally overwhelmed, cycle through the items.", "Focus entirely on each sensation for 30 seconds.", "The intense sensory input competes with the emotional pain signal."], why: "The BPD brain processes emotional pain in the same neural circuits as physical pain (anterior cingulate cortex, insula). Intense but safe sensory input activates competing pathways in the somatosensory cortex, providing genuine neurological relief: not distraction, but actual signal competition.", when: "Crisis moments, urges to self-harm, or emotional pain that feels physical" },
    ],
    emergency: [
      { t: "Ice Dive + STOP Skill", time: "2 min", how: ["S: Stop. Don't act on the urge.", "T: Take a step back. Ice on your face for 30 seconds.", "O: Observe. What emotion is this? Where is it in your body?", "P: Proceed mindfully. What's one wise action you can take?"], why: "STOP prevents impulsive action, the behavior most likely to cause lasting damage during BPD crises. The ice dive between S and O provides the physiological brake that gives the prefrontal cortex time to come back online. Without that neurological pause, the amygdala drives behavior directly.", when: "Crisis, urge to self-harm, relationship rupture, or any moment you want to act on pure emotion" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // AUTISM
  // ─────────────────────────────────────────────────────────────────────────────
  autism: {
    vagal: [
      { t: "Rhythmic Paced Breathing", time: "3 min", how: ["Breathe in for 4 counts through your nose.", "Breathe out for 4 counts through your mouth.", "Keep the rhythm exactly even; use a metronome or tapping if helpful.", "The predictability of the rhythm is more important than the depth."], why: "Autistic nervous systems often have reduced vagal tone and difficulty with interoception (sensing internal states). A rigid, predictable breathing pattern provides external structure that compensates for the internal regulatory challenge. The even rhythm avoids the uncertainty of variable-length breathing exercises.", when: "When you feel dysregulated but can't identify why" },
      { t: "Weighted Vest Breathing", time: "5 min", how: ["Wear a weighted vest (5-10% body weight) or drape a heavy blanket over your shoulders.", "Sit upright and breathe normally.", "Let the weight do the work; don't try to breathe a specific way.", "The pressure provides constant vagal input."], why: "Deep pressure activates slow-adapting mechanoreceptors that provide continuous parasympathetic input. Unlike breathing exercises that require sustained attention and interoception, weighted pressure provides passive vagal stimulation; the nervous system receives calming input without the cognitive load of conscious breathing practice.", when: "Daily regulation, during work or study, or when sensory-seeking" },
    ],
    somatic: [
      { t: "Proprioceptive Input Sequence", time: "5 min", how: ["Wall push-ups: 10 reps, pushing hard against the wall.", "Chair push-ups: press down on armrests and lift your body 5 times.", "Self-hug: wrap arms tight around yourself and squeeze for 10 seconds.", "Joint compressions: press palms together hard for 10 seconds, then interlock fingers and pull apart for 10 seconds."], why: "Proprioception, the sense of body position and force, is often dysregulated in autism, leading to a feeling of being 'unanchored.' Heavy work through muscles and joints activates Golgi tendon organs and muscle spindles that send powerful organizing signals to the cerebellum and somatosensory cortex, literally helping the brain locate itself in space.", when: "When feeling ungrounded, disorganized, or physically restless" },
      { t: "Rhythmic Rocking or Swaying", time: "5 min", how: ["Sit or stand and begin rocking gently: forward/back or side/side.", "Find your natural rhythm; don't force a specific speed.", "Close your eyes if that helps.", "This is not stimming to suppress; it's a valid regulation tool."], why: "Rhythmic vestibular input is one of the most powerful regulators of the autonomic nervous system. The vestibular system has direct connections to the vagus nerve and the locus coeruleus (arousal center). Rocking activates these pathways, reducing arousal and increasing calm. Many autistic people discover this naturally; it works because of neurology, not habit.", when: "Sensory overload, anxiety, or need for self-regulation" },
    ],
    activation: [
      { t: "Swimming or Water Immersion", time: "15 min", how: ["Swim laps, float, or simply be in water.", "If no pool is available, a deep bath provides similar benefits.", "The water provides uniform sensory input across the entire body.", "Focus on the feeling of being held by the water."], why: "Water provides the ideal sensory environment for autistic nervous systems: uniform pressure (proprioceptive), consistent temperature (predictable), muted sound (reduced auditory input), and hydrostatic support (vestibular). This combination reduces sensory processing load while providing enough input to maintain regulation.", when: "After a high-demand social day, or as regular sensory maintenance" },
      { t: "Predictable Rhythmic Exercise", time: "10 min", how: ["Choose repetitive, predictable movement: walking, cycling, rowing, trampolining.", "Maintain a steady, unchanging rhythm.", "Avoid unpredictable group activities or competitive sports.", "Use noise-canceling headphones if in a gym environment."], why: "Predictable rhythmic movement provides the vestibular and proprioceptive input that regulates the autistic nervous system without the sensory unpredictability that can cause overwhelm. The repetition is soothing rather than boring because it matches the nervous system's need for pattern.", when: "Daily regulation, ideally at the same time each day for routine consistency" },
    ],
    coregulation: [
      { t: "Parallel Activity (Low-Demand Connection)", time: "ongoing", how: ["Sit near someone you feel safe with while both doing separate activities.", "Reading, drawing, gaming, crafting: anything works.", "No requirement to talk or make eye contact.", "The shared space is the co-regulation."], why: "Traditional co-regulation techniques assume that eye contact, vocal exchange, and physical proximity are calming. For many autistic people, these are activating. Parallel activity provides the co-regulation benefits of a nearby regulated nervous system without the sensory demands of direct social interaction.", when: "When you want connection without the energy cost of social performance" },
    ],
    sensory: [
      { t: "Sensory Diet Planning", time: "ongoing", how: ["Identify your sensory needs: do you seek or avoid each sense? (touch, sound, light, smell, taste, movement)", "Build a daily plan: scheduled sensory input that feeds your needs.", "Examples: weighted blanket time, noise-canceling headphones, textured fidgets, dim lighting, specific food textures.", "Proactively provide sensory input rather than waiting for overload."], why: "An occupational therapy concept adapted for daily life. Sensory overload is cumulative: by the time you notice it, you're already dysregulated. A sensory diet provides preventive input, keeping the nervous system in its window of tolerance throughout the day rather than cycling between overload and shutdown.", when: "Ongoing lifestyle tool; prevention is better than crisis management" },
      { t: "Noise-Canceling Reset", time: "10 min", how: ["Put on noise-canceling headphones, no music.", "Sit in a dimly lit space.", "Close your eyes.", "Simply exist in the reduced sensory environment for 10 minutes.", "This is a reset, not avoidance."], why: "Autistic sensory processing often involves heightened auditory processing: sounds that neurotypical brains automatically filter require conscious processing in the autistic brain. Noise cancellation reduces this processing load dramatically, freeing up cognitive and emotional resources. The brain literally has fewer competing signals to manage.", when: "After sensory-heavy environments, or when you notice irritability building" },
    ],
    emergency: [
      { t: "Shutdown/Meltdown Protocol", time: "5 min", how: ["Find the nearest low-stimulation space (bathroom, car, quiet room).", "Reduce input: lights off or dim, headphones on, sunglasses if needed.", "Deep pressure: wrap in a blanket, squeeze into a small space, or self-hug.", "Do NOT try to talk, problem-solve, or 'snap out of it.'", "Wait. Your nervous system is rebooting; it needs time, not intervention."], why: "Meltdowns and shutdowns are neurological events, not behavioral choices. They occur when sensory or emotional input exceeds the nervous system's processing capacity. The only effective intervention is input reduction + deep pressure + time. Attempting to talk through it adds more input to an already overloaded system.", when: "During or immediately after a meltdown or shutdown" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // SCHIZOPHRENIA
  // ─────────────────────────────────────────────────────────────────────────────
  schizophrenia: {
    vagal: [
      { t: "Steady Rhythm Breathing", time: "3 min", how: ["Breathe in for 4 counts.", "Breathe out for 4 counts.", "Focus only on counting. Nothing else.", "If your mind wanders, return to 1."], why: "Schizophrenia involves disorganized neural signaling. Simple, rhythmic breathing provides a structured external input that the brain can synchronize to. The counting engages working memory, one of the cognitive functions preserved in most presentations, while the even breathing builds vagal tone. Avoid complex or visualization-heavy techniques.", when: "When thoughts feel disorganized or racing" },
    ],
    somatic: [
      { t: "Grounding Through Five Senses", time: "3 min", how: ["Touch: press your feet hard into the floor.", "See: name 5 objects and their colors.", "Hear: identify 3 sounds in the room.", "Smell: notice any scent present.", "Taste: take a sip of water and focus on the sensation."], why: "Grounding through external senses counters the internal sensory experiences (hallucinations) by flooding the sensory cortex with real-world data. The brain prioritizes external input when it's actively attended to. This doesn't eliminate hallucinations but reduces their intensity by competing for neural processing resources.", when: "When internal experiences feel more real than external reality" },
      { t: "Firm Self-Touch", time: "2 min", how: ["Press your palms together firmly for 10 seconds. Release.", "Squeeze your own arms, firmly but not painfully.", "Pat your legs with flat palms, rhythmically, firmly.", "Feel the boundary of your own body."], why: "Schizophrenia can involve disturbed body boundaries: difficulty distinguishing self from environment. Firm self-touch activates mechanoreceptors that map the physical boundary of your body in the somatosensory cortex. This provides proprioceptive evidence of where 'you' end and the world begins.", when: "When you feel disconnected from your body or reality feels unstable" },
    ],
    activation: [
      { t: "Walking with Counting", time: "10 min", how: ["Walk at a steady pace.", "Count each step: 1, 2, 3, 4, 1, 2, 3, 4.", "Focus on the feeling of your feet hitting the ground.", "If thoughts intrude, return to counting steps."], why: "Walking provides bilateral stimulation and cardiovascular activation that increases prefrontal cortex blood flow. The counting provides an external cognitive anchor that competes with intrusive thoughts. The dual-task nature (walking + counting) engages multiple brain systems simultaneously, reducing resources available for disorganized thought.", when: "Daily, especially when negative symptoms (low motivation, flat affect) are prominent" },
    ],
    coregulation: [
      { t: "Structured Social Time", time: "15 min", how: ["Spend time with a calm, predictable person.", "Choose an activity with clear structure: a board game, cooking a recipe, building something.", "The structure provides a shared focus, reducing social processing demands.", "If conversation feels like too much, the activity speaks for itself."], why: "Social withdrawal in schizophrenia is partly a self-protective response to overwhelming social processing demands. Structured activities reduce the ambiguity of social interaction: there are clear rules, turns, and expectations. This allows co-regulation benefits without the unpredictability that can trigger symptoms.", when: "Regular practice; even brief structured social contact protects against further isolation" },
    ],
    sensory: [
      { t: "Anchoring Object", time: "ongoing", how: ["Choose a small object you can carry: a smooth stone, a coin, a keychain.", "When you need grounding, hold it and focus on every physical detail.", "Associate it with a simple phrase: 'I am here. This is real.'", "The object becomes a portable grounding tool."], why: "The tactile object provides consistent, reliable sensory input that the brain can use as an anchor point. Over time, the association between the object and the grounding phrase creates a conditioned response: touching the object automatically triggers the calming neural pathway.", when: "When reality-testing is needed, or as a general anxiety tool" },
    ],
    emergency: [
      { t: "Reality Testing Protocol", time: "3 min", how: ["Ask yourself: 'Can anyone else see/hear this?'", "Touch something physical; describe it out loud.", "Call your support person and describe what you're experiencing.", "Take your medication if it's been missed.", "Go to a well-lit, populated area if possible."], why: "This isn't about arguing with hallucinations; that can increase distress. It's about systematically gathering external sensory evidence and social reality-testing. Speaking out loud engages the language production areas (Broca's area), which competes with the auditory processing of hallucinations for neural resources.", when: "During acute symptom increase or reality distortion" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // EATING DISORDERS
  // ─────────────────────────────────────────────────────────────────────────────
  eating: {
    vagal: [
      { t: "Pre-Meal Calm Breathing", time: "2 min", how: ["Before eating, sit at the table and close your eyes.", "Breathe in for 4 counts, out for 6 counts.", "Place one hand on your belly.", "Do 5 cycles. Then begin eating."], why: "Eating disorders often involve sympathetic activation around food: the nervous system treats meals as threats. Pre-meal breathing shifts the autonomic balance to parasympathetic (rest-and-digest), which is literally required for healthy digestion. Eating in a sympathetic state impairs nutrient absorption and amplifies GI discomfort, reinforcing food avoidance.", when: "Before every meal; make it a non-negotiable ritual" },
    ],
    somatic: [
      { t: "Gentle Body Neutrality Scan", time: "5 min", how: ["Lie down and close your eyes.", "Move attention through your body, not evaluating, just noticing.", "At each area, say: 'This is my [body part]. It is here.'", "Avoid words like 'good,' 'bad,' 'fat,' 'thin.'", "Just notice existence, not appearance."], why: "Eating disorders distort the somatosensory cortex's body map: the brain's internal representation of the body becomes inaccurate. Body neutrality scanning rebuilds accurate interoception without the evaluative component that triggers distress. You're teaching your brain to sense your body factually rather than judgmentally.", when: "Daily practice, and especially before or after body-checking urges" },
    ],
    activation: [
      { t: "Gentle Movement (Not Exercise)", time: "10 min", how: ["Stretch, walk slowly, do gentle yoga, or dance to music.", "The goal is enjoyment and connection to your body, NOT calorie burning.", "If you catch yourself counting calories, stop and redirect.", "Ask: 'Does my body want to move? How does it want to move?'"], why: "Compulsive exercise is common in eating disorders. Reclaiming movement as joyful rather than compensatory rewires the association between exercise and punishment. Gentle movement also stimulates the vagus nerve through diaphragmatic engagement and improves interoception, helping you reconnect with hunger and fullness cues.", when: "When you want to move but fear the eating disorder will hijack it" },
    ],
    coregulation: [
      { t: "Shared Meal Experience", time: "ongoing", how: ["Eat with someone safe, not someone who comments on food or bodies.", "Let their normal, relaxed relationship with food influence yours.", "You don't have to eat the same thing or the same amount.", "Their calm eating nervous system co-regulates your activated one."], why: "Mirror neurons fire when we watch others eat, creating an automatic simulation of their experience. Eating with someone who has a healthy relationship with food provides a neurological template that your brain can model. This is why family-based treatment (Maudsley) is the most effective eating disorder intervention for adolescents.", when: "As many meals as possible, especially challenging ones" },
    ],
    sensory: [
      { t: "Mindful First Bite", time: "2 min", how: ["Before eating, look at your food. Notice colors and arrangement.", "Smell it. Let your mouth water; this is your body preparing to digest.", "Take the first bite slowly. Chew 15-20 times.", "Notice: temperature, texture, flavor, how it changes as you chew.", "Then eat normally. One mindful bite is enough."], why: "The first bite activates the cephalic phase of digestion: salivary enzymes, stomach acid, and insulin release all begin before food reaches the stomach. Eating disorder behaviors (restricting, bingeing, purging) disrupt this phase. One mindful bite retrains the cephalic response, improving digestion and reconnecting the brain to the body's food processing.", when: "Every meal; it takes 30 seconds and retrains your digestive response" },
    ],
    emergency: [
      { t: "Urge Surfing", time: "5 min", how: ["Notice the urge (to restrict, binge, purge, or exercise).", "Rate its intensity: 1-10.", "Set a timer for 5 minutes.", "Observe the urge like a wave: it rises, peaks, and falls.", "Don't fight it. Don't act on it. Just watch it.", "Check the intensity again after 5 minutes."], why: "Eating disorder urges follow the same neurological pattern as any craving: they spike, peak, and decline. Acting on the urge reinforces the neural pathway (negative reinforcement). Surfing the urge without acting teaches the brain that the discomfort is survivable, gradually weakening the compulsion pathway through extinction.", when: "When the urge to engage in eating disorder behavior is strong" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // NEURO CORE (General Brain Optimization)
  // ─────────────────────────────────────────────────────────────────────────────
  neuro_core: {
    vagal: [
      { t: "Heart Rate Variability Training", time: "5 min", how: ["Breathe at 6 breaths per minute: inhale 5 seconds, exhale 5 seconds.", "This specific rhythm maximizes heart rate variability (HRV).", "Place a hand on your chest to feel the rhythm.", "Practice for 5 minutes daily; consistency beats duration."], why: "HRV is the gold standard measure of vagal tone and autonomic flexibility. Breathing at 0.1 Hz (6 breaths/min) creates resonance between respiratory and cardiac oscillations, maximizing HRV. Higher HRV correlates with better emotional regulation, cognitive flexibility, and stress resilience: the foundations of brain optimization.", when: "Daily practice, morning is ideal for setting the day's autonomic tone" },
      { t: "Cold Exposure Protocol", time: "3 min", how: ["End your shower with 30-60 seconds of cold water (as cold as it goes).", "Or: submerge face in ice water for 15-30 seconds, 3 reps.", "Breathe steadily through the discomfort; don't gasp.", "Gradually increase duration over weeks."], why: "Deliberate cold exposure triggers norepinephrine release (200-300%), activates brown fat thermogenesis, reduces inflammation, and builds stress resilience through hormesis. Regular practice increases vagal tone, improves immune function, and enhances the brain's ability to maintain calm under pressure.", when: "Daily, morning cold exposure sets catecholamine levels for the entire day" },
    ],
    somatic: [
      { t: "Interoceptive Awareness Training", time: "5 min", how: ["Sit quietly and attempt to feel your heartbeat without touching your chest.", "Count heartbeats for 30 seconds. Then check with your fingers.", "How accurate were you?", "Practice daily; accuracy improves with training."], why: "Interoceptive accuracy, the ability to sense internal body states, is the foundation of emotional intelligence and self-regulation. Research shows it predicts decision-making quality, emotional regulation, and even intuition accuracy. This is a trainable skill that directly improves the insula's processing capacity.", when: "Daily practice; this is brain training for emotional intelligence" },
      { t: "Cross-Body Coordination Drill", time: "3 min", how: ["Touch right hand to left knee, then left hand to right knee. Alternate for 30 seconds.", "Right elbow to left knee, then left elbow to right knee. 30 seconds.", "Right hand touches left heel behind your back. Alternate. 30 seconds.", "Make it harder: add counting backwards from 100 by 7s."], why: "Cross-body movements force communication between brain hemispheres through the corpus callosum. Adding cognitive load (counting backwards) creates a dual-task challenge that strengthens the prefrontal cortex's ability to coordinate multiple processes, the exact capacity that underlies executive function.", when: "Morning routine or before cognitively demanding work" },
    ],
    activation: [
      { t: "Zone 2 Cardio", time: "20 min", how: ["Exercise at an intensity where you can hold a conversation but it's slightly uncomfortable.", "Walking uphill, easy jogging, cycling, swimming: any modality works.", "You should be able to breathe through your nose the entire time.", "This is NOT high intensity; it should feel sustainable."], why: "Zone 2 cardio is the most evidence-based exercise for brain health. It increases BDNF (brain-derived neurotrophic factor) by 200-300%, improves cerebral blood flow, enhances mitochondrial density in neurons, and promotes neurogenesis in the hippocampus. Andrew Huberman, Peter Attia, and every longevity researcher agrees: Zone 2 is king.", when: "3-5 times per week; this is the single highest-ROI activity for brain health" },
      { t: "Morning Sunlight Protocol", time: "10 min", how: ["Within 30 minutes of waking, get outside.", "Look toward the sky (never directly at the sun).", "No sunglasses; you need the full spectrum hitting your retinas.", "Stay for 10 minutes minimum, even on cloudy days."], why: "Morning light exposure triggers the suprachiasmatic nucleus to set the circadian master clock, suppresses melatonin, initiates the cortisol awakening response, and sets the timer for evening melatonin release 14-16 hours later. This single intervention improves sleep, mood, focus, and metabolic health. It's free and takes 10 minutes.", when: "Every single morning; non-negotiable for brain optimization" },
    ],
    coregulation: [
      { t: "Deep Conversation Practice", time: "15 min", how: ["Have a genuine conversation about something meaningful with someone.", "Practice active listening: reflect back what you heard before responding.", "Maintain gentle eye contact (not staring, not avoiding).", "Notice your own emotional responses during the conversation."], why: "Deep social connection activates the ventral vagal complex, releases oxytocin, and exercises the social engagement system, the most evolutionarily recent and sophisticated part of the autonomic nervous system. Regular deep conversation literally keeps the social neural circuits calibrated and functional.", when: "Daily; social connection is not optional for brain optimization" },
    ],
    sensory: [
      { t: "Non-Sleep Deep Rest (NSDR)", time: "10 min", how: ["Lie down, close your eyes.", "Progressively relax body parts from feet to head.", "Once fully relaxed, focus on the space behind your closed eyelids.", "Don't try to sleep. Just rest in conscious relaxation.", "If you drift off, that's fine."], why: "NSDR (Andrew Huberman's term for yoga nidra-style protocols) increases striatal dopamine by 65%, restores cognitive function equivalent to a nap, and enhances neuroplasticity. It shifts brainwaves to alpha/theta without the sleep inertia of actual napping. It's the most efficient form of neural recovery available.", when: "After learning something new, post-lunch dip, or whenever cognitive performance drops" },
    ],
    emergency: [
      { t: "Physiological Sigh + Box Breathing Combo", time: "2 min", how: ["Start with 2-3 physiological sighs (double inhale, long exhale).", "Then transition to box breathing: 4 in, 4 hold, 4 out, 4 hold.", "Continue box breathing for 1-2 minutes.", "The sighs provide instant calm; the box breathing sustains it."], why: "The physiological sigh is the fastest reset. Box breathing provides sustained regulation. Combining them in sequence gives you both immediate and lasting nervous system control. Navy SEALs use this exact protocol for stress inoculation.", when: "High-pressure situations, before presentations, or any acute stress" },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // DEFAULT (General / No Specific Condition)
  // ─────────────────────────────────────────────────────────────────────────────
  default: {
    vagal: [
      { t: "4-7-8 Breathing", time: "3 min", how: ["Inhale through your nose for 4 counts.", "Hold gently for 7 counts.", "Exhale through your mouth for 8 counts.", "Repeat 4-6 cycles."], why: "The extended exhale directly stimulates the vagus nerve, shifting your autonomic nervous system from sympathetic (stress) to parasympathetic (calm). The hold allows CO2 to build slightly, reducing the breathing rate and calming the chemoreceptors that drive the urge to breathe faster during stress.", when: "Anytime you need to calm down quickly" },
      { t: "Humming Vagal Tone", time: "3 min", how: ["Inhale deeply.", "Exhale while humming at a comfortable pitch.", "Feel the vibration in your chest and throat.", "Repeat for 3 minutes."], why: "Humming vibrates the vagus nerve where it passes through the throat, directly stimulating parasympathetic activity. Regular practice builds vagal tone, the baseline level of vagal activity that determines your ability to recover from stress.", when: "Daily practice to build stress resilience" },
      { t: "Cold Water Vagal Reset", time: "1 min", how: ["Splash very cold water on your face, or submerge your face in cold water for 15-30 seconds.", "The key areas: forehead, cheeks, and around the eyes.", "Breathe steadily.", "Repeat 2-3 times."], why: "Cold on the face activates the trigeminal nerve, triggering the mammalian dive reflex. Heart rate drops 10-25% immediately. This is the fastest way to shift from sympathetic to parasympathetic dominance, faster than any breathing technique.", when: "Acute stress, anxiety, or when you need an instant reset" },
    ],
    somatic: [
      { t: "5-4-3-2-1 Grounding", time: "3 min", how: ["Name 5 things you can see.", "Name 4 things you can touch.", "Name 3 things you can hear.", "Name 2 things you can smell.", "Name 1 thing you can taste."], why: "This technique forces the brain into present-moment sensory processing, activating the somatosensory cortex and deactivating the default mode network (which generates worry and rumination). You cannot be sensorily present and mentally time-traveling simultaneously.", when: "Worry, rumination, or feeling disconnected from the present" },
      { t: "Progressive Muscle Relaxation", time: "5 min", how: ["Start at your feet: tense all muscles hard for 5 seconds.", "Release completely. Notice the contrast.", "Move up: calves, thighs, glutes, abs, hands, arms, shoulders, face.", "Tense each group for 5 seconds, then fully release."], why: "The tense-release cycle activates the Golgi tendon organs, which send inhibitory signals to the muscles and through the spinal cord to the brain. This creates genuine physical relaxation that the brain can learn to associate with safety.", when: "Before sleep, during stress, or when tension is building" },
    ],
    activation: [
      { t: "Morning Light + Walk", time: "10 min", how: ["Get outside within 30 minutes of waking.", "Walk at a comfortable pace for 10 minutes.", "Look toward the sky (not directly at sun) for light exposure.", "Breathe through your nose."], why: "Morning light sets your circadian clock, suppresses melatonin, and initiates the cortisol awakening response. Walking adds bilateral stimulation and mild cardiovascular activation. This combination is the single most impactful morning habit for mental and physical health.", when: "Every morning; this is foundational" },
      { t: "Shake and Release", time: "3 min", how: ["Stand with slightly bent knees.", "Begin bouncing, letting your whole body shake loose.", "Arms, jaw, shoulders: let everything go.", "Shake for 2-3 minutes, then stand still and notice the shift."], why: "Animals shake after surviving a threat to discharge the freeze response. Humans suppress this reflex. Intentional shaking releases stored muscular tension and shifts the nervous system from freeze/shutdown to alertness and calm.", when: "When feeling stuck, heavy, or tense" },
    ],
    coregulation: [
      { t: "Safe Person Connection", time: "5 min", how: ["Call or sit with someone whose presence makes you feel safe.", "You don't need to talk about what's wrong.", "Just be in their presence and let your nervous system sync.", "Notice: does your breathing slow? Do your shoulders drop?"], why: "A regulated nervous system in proximity literally transmits safety signals through voice, facial expression, and breathing patterns. This co-regulation is the original way humans manage stress; we are not designed to regulate alone.", when: "When self-regulation isn't enough, or you need support" },
    ],
    sensory: [
      { t: "Weighted Blanket Rest", time: "10 min", how: ["Lie under a weighted blanket (10-15% of body weight).", "Close your eyes and breathe normally.", "Let the weight provide passive calming input.", "No need to do anything; just rest."], why: "Deep pressure touch activates the parasympathetic system through skin mechanoreceptors. Research shows it reduces cortisol by 31% and increases serotonin by 28%. The effect is passive: your nervous system receives calming input without any effort.", when: "Evening wind-down, anxiety, or anytime you need passive calming" },
    ],
    emergency: [
      { t: "Physiological Sigh", time: "30 sec", how: ["Double inhale through the nose (two quick sniffs).", "One long, slow exhale through the mouth.", "Repeat 2-3 times.", "This works in under 30 seconds."], why: "The fastest known method to activate the parasympathetic nervous system. The double inhale reinflates collapsed alveoli, maximizing CO2 offloading on the exhale. One to three cycles can shift your entire autonomic state.", when: "Any moment you need instant calm" },
      { t: "TIPP: Temperature", time: "1 min", how: ["Apply ice or very cold water to your face.", "Hold for 30-60 seconds.", "Breathe slowly through the cold.", "Notice the immediate heart rate drop."], why: "Temperature change is the fastest way to change body chemistry. Cold on the face activates the dive reflex, an involuntary parasympathetic response that overrides sympathetic activation.", when: "Panic, acute stress, or emotional overwhelm" },
    ],
  },
};
